version: '3.11'

services:
  interview:
    image: pashte04/interview:p6438
    restart: always
    environment:
      APP_SETTINGS: "config.Config"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    expose:
      - "5000"
    entrypoint: /app/entrypoint.sh
  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${PWD}/config/postgresql.conf:/etc/postgresql/postgresql.conf
  web:
    image: nginx:1.19.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf:ro
