"""empty message

Revision ID: 22fca886a2ea
Revises: f46382d03c17
Create Date: 2020-10-13 17:51:42.637885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fca886a2ea'
down_revision = 'f46382d03c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
